import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("  antialiased grainy font-sans", inter.variable)}>
        <div vaul-drawer-wrapper="" className="min-h-screen bg-background">
          {children}
        </div>
        <Toaster position="top-center" richColors theme="light" />
      </body>
    </html>
  );
}
